DELETE FROM telefone;
DELETE FROM endereco;
DELETE FROM pessoa;

ALTER SEQUENCE telefone_id_seq RESTART WITH 1;
ALTER SEQUENCE endereco_id_seq RESTART WITH 1;
ALTER SEQUENCE pessoa_id_seq RESTART WITH 1;